In [1]:
print("hello world")

hello world

In [2]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (2.4.2)
Requirement already satisfied: matplotlib in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satindra kumar b s\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\satindra kumar b s\appdata\roaming\python\python312\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\satindra kumar b s\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\satindra kumar b s\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("health_fitness_dataset.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'health_fitness_dataset.csv'

In [ ]:
df=pd.read_csv("health_fitness_dataset.csv")
df.head()

,participant_id,date,age,gender,height_cm,weight_kg,activity_type,duration_minutes,intensity,calories_burned,...,stress_level,daily_steps,hydration_level,bmi,resting_heart_rate,blood_pressure_systolic,blood_pressure_diastolic,health_condition,smoking_status,fitness_level
0,1,2024-01-01,56,F,165.3,53.7,Dancing,41,Low,3.3,...,3,7128,1.5,19.6,69.5,110.7,72.9,NaN,Never,0.04
1,1,2024-01-04,56,F,165.3,53.9,Swimming,28,Low,2.9,...,7,7925,1.8,19.6,69.5,110.7,72.9,NaN,Never,0.07
2,1,2024-01-05,56,F,165.3,54.2,Swimming,21,Medium,2.6,...,7,7557,2.7,19.6,69.5,110.7,72.9,NaN,Never,0.09
3,1,2024-01-07,56,F,165.3,54.4,Weight Training,99,Medium,10.7,...,8,11120,2.6,19.6,69.5,110.7,72.9,NaN,Never,0.21
4,1,2024-01-09,56,F,165.3,54.7,Swimming,100,Medium,12.7,...,1,5406,1.5,19.6,69.5,110.7,72.9,NaN,Never,0.33

In [ ]:
df.isnull().sum()

participant_id                   0
date                             0
age                              0
gender                           0
height_cm                        0
weight_kg                        0
activity_type                    0
duration_minutes                 0
intensity                        0
calories_burned                  0
avg_heart_rate                   0
hours_sleep                      0
stress_level                     0
daily_steps                      0
hydration_level                  0
bmi                              0
resting_heart_rate               0
blood_pressure_systolic          0
blood_pressure_diastolic         0
health_condition            490275
smoking_status                   0
fitness_level                    0
dtype: int64

In [ ]:
df=pd.read_csv("Fitness_Health_Tracking_Dataset.csv")
df.head()

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,01-01-2023 00:00,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,02-01-2023 00:00,19,Female,191,80,7010,1806,NaN,3.103590,47.0,72.0,Cardio,9,Neutral
2,1,Sara Martinez,03-01-2023 00:00,19,Female,191,80,18942,2274,8.167817,3.814843,46.0,85.0,Yoga,6,Sad
3,1,Sara Martinez,04-01-2023 00:00,19,Female,191,80,13778,2656,7.453552,3.508636,105.0,77.0,Yoga,2,Sad
4,1,Sara Martinez,05-01-2023 00:00,19,Female,191,80,10247,3571,5.132654,NaN,53.0,61.0,Yoga,8,Sad

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   36500 non-null  str
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            32841 non-null  float64
 10  Water_Intake (Liters)  31099 non-null  float64
 11  Active_Minutes         34633 non-null  float64
 12  Heart_Rate (bpm)       34668 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: float64(4), int64(7), str(5)
memory usage: 4.5 MB

In [ ]:
df.isnull().sum()

User_ID                     0
Full Name                   0
Date                        0
Age                         0
Gender                      0
Height (cm)                 0
Weight (kg)                 0
Steps_Taken                 0
Calories_Burned             0
Hours_Slept              3659
Water_Intake (Liters)    5401
Active_Minutes           1867
Heart_Rate (bpm)         1832
Workout_Type             9192
Stress_Level (1-10)         0
Mood                        0
dtype: int64

In [ ]:
df.shape

(36500, 16)

In [ ]:
df.head()

,User_ID,Full Name,Date,Age,Gender,Height (cm),Weight (kg),Steps_Taken,Calories_Burned,Hours_Slept,Water_Intake (Liters),Active_Minutes,Heart_Rate (bpm),Workout_Type,Stress_Level (1-10),Mood
0,1,Sara Martinez,01-01-2023 00:00,19,Female,191,80,11405,1862,7.021201,3.440508,80.0,84.0,Yoga,2,Happy
1,1,Sara Martinez,02-01-2023 00:00,19,Female,191,80,7010,1806,NaN,3.103590,47.0,72.0,Cardio,9,Neutral
2,1,Sara Martinez,03-01-2023 00:00,19,Female,191,80,18942,2274,8.167817,3.814843,46.0,85.0,Yoga,6,Sad
3,1,Sara Martinez,04-01-2023 00:00,19,Female,191,80,13778,2656,7.453552,3.508636,105.0,77.0,Yoga,2,Sad
4,1,Sara Martinez,05-01-2023 00:00,19,Female,191,80,10247,3571,5.132654,NaN,53.0,61.0,Yoga,8,Sad

In [ ]:
df.isnull().values.any()

np.True_

In [ ]:
df.isnull().sum().sum()

np.int64(21951)

In [ ]:
df["Date"]=pd.to_datetime(df["Date"], errors='coerce')

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
df=pd.read_csv("Fitness_Health_Tracking_Dataset.csv")

In [ ]:
df["Date"]=pd.to_datetime(df["Date"], errors='coerce')

In [ ]:
df["Workout_Type"].value_counts()

Workout_Type
Yoga        9222
Cardio      9048
Strength    9038
Name: count, dtype: int64

In [ ]:
9222+9048+9038-36500

-9192

In [ ]:
df["Workout_Type"]=df["Workout_Type"].fillna("No Workout")

In [ ]:
df["Workout_Type"].value_counts()

Workout_Type
Yoga          9222
No Workout    9192
Cardio        9048
Strength      9038
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

User_ID                      0
Full Name                    0
Date                     22100
Age                          0
Gender                       0
Height (cm)                  0
Weight (kg)                  0
Steps_Taken                  0
Calories_Burned              0
Hours_Slept               3659
Water_Intake (Liters)     5401
Active_Minutes            1867
Heart_Rate (bpm)          1832
Workout_Type                 0
Stress_Level (1-10)          0
Mood                         0
dtype: int64

In [6]:
import pandas as pd
df=pd.read_csv("Fitness_Health_Tracking_Dataset.csv")

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36500 entries, 0 to 36499
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   User_ID                36500 non-null  int64
 1   Full Name              36500 non-null  str
 2   Date                   36500 non-null  str
 3   Age                    36500 non-null  int64
 4   Gender                 36500 non-null  str
 5   Height (cm)            36500 non-null  int64
 6   Weight (kg)            36500 non-null  int64
 7   Steps_Taken            36500 non-null  int64
 8   Calories_Burned        36500 non-null  int64
 9   Hours_Slept            32841 non-null  float64
 10  Water_Intake (Liters)  31099 non-null  float64
 11  Active_Minutes         34633 non-null  float64
 12  Heart_Rate (bpm)       34668 non-null  float64
 13  Workout_Type           27308 non-null  str
 14  Stress_Level (1-10)    36500 non-null  int64
 15  Mood                   36500 non-null  str
dtypes: float64(4), int64(7), str(5)
memory usage: 4.5 MB